### PR TITLE
Select default dates and select dates programmatically 

### PR DESCRIPTION
**Pull request by gsalgadotoledo**
Thanks for such a simple and powerful calendar.

I'm trying to set up a selected  date programmatically but it doesn't select me the today's day when the calendar loads

```vue
<date-picker
      :value="{ first: new Date(), last: new Date() }"
      @input="onChange"
      :panels="2"
      :mode="mode"
      :width="245"
    />
```

I'd like to be able to change the selected date from the code also through a variable, something like this

```vue
<date-picker
      :value="selectedDate"
      @input="onChange"
      :panels="2"
      :mode="mode"
      :width="245"
    />
```

```js
const today = new Date();
const tomorrow = new Date();

today.setHours(0,0,0,0)
tomorrow.setDate(today.getDate() + 1);
tomorrow.setHours(0,0,0,0)
this.selectedDate = { first: today, last: tomorrow }
```

do you think am I missing something? or maybe we can just add a watch in the component could solve it?

I tested it and it works fine for my case

### CODE REVIEW

**Comment by mikhailvs** [comment]
I believe the issue with the first snippet is that you are not specifying a valid mode. Try using this code:
```js
<date-picker
      :value="new Date()"
      @input="onChange"
      :panels="2"
      :mode="single"
      :width="245"
    />
```

**Comment by gsalgadotoledo** [comment]
Mode was a variable, I tested it that way though and still doesn't show the today's date with the selected CSS class

Screen Shot 2019-07-11 at 10 18 56 AM

Screen Shot 2019-07-11 at 10 16 06 AM

Screen Shot 2019-07-11 at 9 30 21 AM

Screen Shot 2019-07-11 at 9 33 47 AM

I'm using `"v-cal-input": "^0.1.9",` version

**Comment by gsalgadotoledo** [comment]
I don't have experience on Vue, I wonder how the value prop makes an effect in the DatePicker component:
```
      value: {
        type: [Date, Object],
        default: () => ({ first: null, last: null })
      },
```

**Comment by gsalgadotoledo** [comment]
I just found out a way to make it work, I'm using a ref in the date picker component:
```js
<date-picker
      ref="DatePicker"
      :value="new Date()"
      @input="onChange"
      :panels="2"
      :mode="single"
      :width="245"
    />
```

And then I can set the internal state (data) through this ref this way:
```js
  mounted() {
      this.$refs.DatePicker.selection = { first: now, last: null }
  },
```

For the records in my case for some reason the value attribute it's not making any effect, so if someone is having the same issue they can use this approach ^^

Also to make it select the current day I needed to set the now date-time hours to 0 and set that date as first in a key-value object even if the mode is set as `single`

```js
      const now = new Date()
      now.setHours(0, 0, 0, 0)
      this.$refs.DatePicker.selection = { first: now, last: null }
```

**Pull request closed without merging**
